application.Main/Controllers/rechargeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using application.Main.ViewModels;
using application.Main.Models;
using RestSharp;
using Newtonsoft.Json;

namespace application.Main.Controllers
{
    public class rechargeController : Controller
    {
        // GET: recharge
        public ActionResult Prepaid()
        {
            string accessToken = Helper.decryptAndRetrieveCookieValue(Helper.userAccessToken);
            if (String.IsNullOrEmpty(accessToken))
                return RedirectToAction("index", new { Controller = "unauthorized" });
            rechargeVM objRechargeVM = new rechargeVM();
            IRestResponse webAPIResponse = Helper.WebAPIClient_via_RestSharp("getRechargeServiceList?serviceType=PREPAID", Method.GET, null, accessToken);
            if (webAPIResponse.StatusCode == System.Net.HttpStatusCode.OK)
            {
                objRechargeVM = JsonConvert.DeserializeObject<rechargeVM>(webAPIResponse.Content);
            }
            objRechargeVM.Title = "Prepaid Mobile Recharge";
            return View("index", objRechargeVM);
        }

        public ActionResult Postpaid()
        {
            string accessToken = Helper.decryptAndRetrieveCookieValue(Helper.userAccessToken);
            if (String.IsNullOrEmpty(accessToken))
                return RedirectToAction("index", new { Controller = "unauthorized" });
            rechargeVM objRechargeVM = new rechargeVM();
            IRestResponse webAPIResponse = Helper.WebAPIClient_via_RestSharp("getRechargeServiceList?serviceType=POSTPAID", Method.GET, null, accessToken);
            if (webAPIResponse.StatusCode == System.Net.HttpStatusCode.OK)
            {
                objRechargeVM = JsonConvert.DeserializeObject<rechargeVM>(webAPIResponse.Content);
            }
            objRechargeVM.Title = "Postpaid Mobile Recharge";
            return View("index", objRechargeVM);
        }

        public ActionResult DTH()
        {
            string accessToken = Helper.decryptAndRetrieveCookieValue(Helper.userAccessToken);
            if (String.IsNullOrEmpty(accessToken))
                return RedirectToAction("index", new { Controller = "unauthorized" });
            rechargeVM objRechargeVM = new rechargeVM();
            IRestResponse webAPIResponse = Helper.WebAPIClient_via_RestSharp("getRechargeServiceList?serviceType=DTH", Method.GET, null, accessToken);
            if (webAPIResponse.StatusCode == System.Net.HttpStatusCode.OK)
            {
                objRechargeVM = JsonConvert.DeserializeObject<rechargeVM>(webAPIResponse.Content);
            }
            objRechargeVM.Title = "DTH Recharge";
            return View("dthRecharge", objRechargeVM);
        }

        public ActionResult history()
        {
            string accessToken = Helper.decryptAndRetrieveCookieValue(Helper.userAccessToken);
            if (String.IsNullOrEmpty(accessToken))
                return RedirectToAction("index", new { Controller = "unauthorized" });
            return View("rechargeHistory");
        }

        private Boolean hasAvailableBalance(double amount, string accessToken)
        {
            IRestResponse response = Helper.WebAPIClient_via_RestSharp("instantPayRecharge/checkavailableBalance", Method.GET, null, accessToken);
            if (response.StatusCode == System.Net.HttpStatusCode.OK)
            {
                double availableBalance = JsonConvert.DeserializeObject<double>(response.Content);
                if (availableBalance > amount)
                    return true;
                else
                    return false;
            }
            else
            {
                return false;
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult transactRecharge(rechargeVM objRecharge)
        {
            try
            {
                customResponse objCustomResponse = new customResponse();
                string accessToken = Helper.decryptAndRetrieveCookieValue(Helper.userAccessToken);
                if (String.IsNullOrEmpty(accessToken))
                    return Json(new { success = false, responseText = "Unauthorized", redirectURL = Url.Content("~/Unauthorized") }, JsonRequestBehavior.AllowGet);

                if (objRecharge.objRechargeTransaction.Amount > 0)
                {
                    if (hasAvailableBalance(Convert.ToDouble(objRecharge.objRechargeTransaction.Amount), accessToken))
                    {
                        if (Helper.hasEnoughWalletBalance(Convert.ToDecimal(objRecharge.objRechargeTransaction.Amount), accessToken))
                        {
                            objRecharge.objRechargeTransaction.customermobile = objRecharge.objRechargeTransaction.MobileNo;
                            IRestResponse rechargeReponse = Helper.WebAPIClient_via_RestSharp("instantPayRecharge/rechargeMobile", Method.POST, objRecharge.objRechargeTransaction, accessToken);
                            if (rechargeReponse.StatusCode == System.Net.HttpStatusCode.OK)
                            {
                                TempData[Helper.responseStatus] = "Transaction has been successfully processed.";
                                return Json(new { success = true, responseText = "0|Recharge Successfully Done" }, JsonRequestBehavior.AllowGet);
                            }
                            else
                            {
                                objCustomResponse = JsonConvert.DeserializeObject<customResponse>(rechargeReponse.Content);
                                return Json(new { success = true, responseText = "1|" + objCustomResponse.Message }, JsonRequestBehavior.AllowGet);
                            }
                        }
                        else
                        {
                            return Json(new { success = false, responseText = "1|Oops! Wallet Balance is too Low" }, JsonRequestBehavior.AllowGet);
                        }
                    }
                    else
                    {
                        return Json(new { success = false, responseText = "1|Oops! There is some issue with Recharge. Kindly contact administrator. ErrorCode:(balanceAvailibility)" }, JsonRequestBehavior.AllowGet);
                    }
                }
                else
                {
                    return Json(new { success = false, responseText = "1|Invalid Amount to Transfer. Kindly input proper amount" }, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception ex)
            {
                return Json(new { success = false, responseText = "1|" + ex.Message.ToString() }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult transactDTHRecharge(rechargeVM objRecharge)
        {
            try
            {
                customResponse objCustomResponse = new customResponse();
                string accessToken = Helper.decryptAndRetrieveCookieValue(Helper.userAccessToken);
                if (String.IsNullOrEmpty(accessToken))
                    return Json(new { success = false, responseText = "Unauthorized", redirectURL = Url.Content("~/Unauthorized") }, JsonRequestBehavior.AllowGet);

                if (objRecharge.objRechargeTransaction.Amount > 0)
                {
                    if (hasAvailableBalance(Convert.ToDouble(objRecharge.objRechargeTransaction.Amount), accessToken))
                    {
                        if (Helper.hasEnoughWalletBalance(Convert.ToDecimal(objRecharge.objRechargeTransaction.Amount), accessToken))
                        {
                            IRestResponse rechargeReponse = Helper.WebAPIClient_via_RestSharp("instantPayRecharge/rechargeMobile", Method.POST, objRecharge.objRechargeTransaction, accessToken);
                            if (rechargeReponse.StatusCode == System.Net.HttpStatusCode.OK)
                            {
                                TempData[Helper.responseStatus] = "Transaction has been successfully processed.";
                                return Json(new { success = true, responseText = "0|Recharge Successfully Done" }, JsonRequestBehavior.AllowGet);
                            }
                            else
                            {
                                objCustomResponse = JsonConvert.DeserializeObject<customResponse>(rechargeReponse.Content);
                                return Json(new { success = true, responseText = "1|" + objCustomResponse.Message }, JsonRequestBehavior.AllowGet);
                            }
                        }
                        else
                        {
                            return Json(new { success = false, responseText = "1|Oops! Wallet Balance is too Low" }, JsonRequestBehavior.AllowGet);
                        }
                    }
                    else
                    {
                        return Json(new { success = false, responseText = "1|Oops! There is some issue with Recharge. Kindly contact administrator. ErrorCode:(balanceAvailibility)" }, JsonRequestBehavior.AllowGet);
                    }
                }
                else
                {
                    return Json(new { success = false, responseText = "1|Invalid Amount to Transfer. Kindly input proper amount" }, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception ex)
            {
                return Json(new { success = false, responseText = "1|" + ex.Message.ToString() }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpGet]
        public JsonResult getRechargeHistory(string fromDate, string toDate)
        {
            //Server Side Parameter
            string accessToken = Helper.decryptAndRetrieveCookieValue(Helper.userAccessToken);

application.Main/Views/recharge/dthRecharge.cshtml
@model  application.Main.ViewModels.rechargeVM
@{
    ViewBag.Title = "DMR";
    Layout = "~/Views/Shared/_Layout.cshtml";
    @Styles.Render("~/bundles/datatablescss")
    <style>
        .modal.show .modal-dialog {
            margin-top: 15%;
        }
    </style>
}
<div class="content-body">
    <div class="row justify-content-md-center">
        <div class="col-md-5">
            <div class="card">
                <div class="card-header">
                    <div class="card-text text-center">
                        <h2 class="title">@Html.DisplayFor(model => model.Title)</h2>
                    </div>
                </div>
                <div class="card-content">
                    <div class="card-body">
                        @using (Ajax.BeginForm("transactDTHRecharge", "recharge", new AjaxOptions { OnBegin = "beginSubmit('btnSubmit')", OnComplete = "completeSubmit('btnSubmit','Submit')", OnSuccess = "OnSuccess", OnFailure = "OnFailure", LoadingElementId = "process-loading" }, new { @class = "form form-horizontal" }))
                        {
                            @Html.AntiForgeryToken();
                            <div class="form-body">
                                <div class="form-group row">
                                    <div class="col-12">
                                        <label>Select DTH Type</label>
                                        @Html.DropDownListFor(model => model.objRechargeTransaction.InstantPayRechargeDataId, new SelectList(Model.objInstantPayUtilityDataList, "InstantPayRechargeDataId", "ServiceName"), "--- Select Provider ---", new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.objRechargeTransaction.InstantPayRechargeDataId, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <div class="col-12">
                                        <label>Enter DTH No.</label>
                                        @Html.EditorFor(model => model.objRechargeTransaction.MobileNo, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter DTH Number", @maxlength = "10" } })
                                        @Html.ValidationMessageFor(model => model.objRechargeTransaction.MobileNo, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <div class="col-12">
                                        <label>Enter Mobile No. registered with DTH</label>
                                        @Html.EditorFor(model => model.objRechargeTransaction.customermobile, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Customer Mobile No.", @maxlength = "10" } })
                                        @Html.ValidationMessageFor(model => model.objRechargeTransaction.customermobile, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <div class="col-12">
                                        <label>Enter Amount</label>
                                        @Html.EditorFor(model => model.objRechargeTransaction.Amount, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Amount" } })
                                        @Html.ValidationMessageFor(model => model.objRechargeTransaction.Amount, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="form-group text-center">
                                    @*<button type="submit" class="btn btn-shade1" id="btnSubmit">
                                        Submit
                                    </button>*@
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@section scripts{
    @Scripts.Render("~/bundles/jqueryval");
    <script>
         $(function () {
            var showMessage = '@TempData[Helper.responseStatus]'
             if (showMessage != '')
                 notifyMessage(showMessage);
         });
    </script>
}

application.Main/Views/recharge/index.cshtml
@model  application.Main.ViewModels.rechargeVM
@{
    ViewBag.Title = "DMR";
    Layout = "~/Views/Shared/_Layout.cshtml";
    @Styles.Render("~/bundles/datatablescss")
    <style>
        .modal.show .modal-dialog {
            margin-top: 15%;
        }
    </style>
}
<div class="content-body">
    <div class="row justify-content-md-center">
        <div class="col-md-5">
            <div class="card">
                <div class="card-header">
                    <div class="card-text text-center">
                        <h2 class="title">@Html.DisplayFor(model => model.Title)</h2>
                    </div>
                </div>
                <div class="card-content">
                    <div class="card-body">
                        @using (Ajax.BeginForm("transactRecharge", "recharge", new AjaxOptions { OnBegin = "beginSubmit('btnSubmit')", OnComplete = "completeSubmit('btnSubmit','Submit')", OnSuccess = "OnSuccess", OnFailure = "OnFailure", LoadingElementId = "process-loading" }, new { @class = "form form-horizontal" }))
                        {
                            @Html.AntiForgeryToken();
                            <div class="form-body">
                                <div class="form-group row">
                                    <div class="col-12">
                                        @Html.DropDownListFor(model => model.objRechargeTransaction.InstantPayRechargeDataId, new SelectList(Model.objInstantPayUtilityDataList, "InstantPayRechargeDataId", "ServiceName"), "--- Select Provider ---", new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.objRechargeTransaction.InstantPayRechargeDataId, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <div class="col-12">
                                        @Html.EditorFor(model => model.objRechargeTransaction.MobileNo, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Mobile No.", @maxlength = "10" } })
                                        @Html.ValidationMessageFor(model => model.objRechargeTransaction.MobileNo, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <div class="col-12">
                                        @Html.EditorFor(model => model.objRechargeTransaction.Amount, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Amount" } })
                                        @Html.ValidationMessageFor(model => model.objRechargeTransaction.Amount, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="form-group text-center">
                                    @*<button type="submit" class="btn btn-shade1" id="btnSubmit">
                                        Submit
                                    </button>*@
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@section scripts{
    @Scripts.Render("~/bundles/jqueryval");
    <script>
         $(function () {
            var showMessage = '@TempData[Helper.responseStatus]'
             if (showMessage != '')
                 notifyMessage(showMessage);
         });
    </script>
}

application.Main/Views/recharge/rechargeHistory.cshtml
@{
    ViewBag.Title = "Recharge History";
    Layout = "~/Views/Shared/_Layout.cshtml";
    @Styles.Render("~/bundles/datatablescss")
}
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.css">
<div class="content-header row mb-2">
    <div class="content-header-left col-md-6 col-12">
        <h2 class="content-header-title title">Recharge History</h2>
    </div>
</div>
<div class="content-body">
    <section id="number-tabs">
        <div class="row">
            <div class="col-12 p-1">
                <div class="card">
                    <div class="card-content">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="row">
                                        <div class="col-md-2"><label for="from">From</label><input type="text" id="fromDate" name="from" class="form-control form-control-sm"></div>
                                        <div class="col-md-2"><label for="to">To</label><input type="text" id="toDate" name="to" class="form-control form-control-sm"></div>
                                        <div class="col-md-2 text-left pt-26"><input type="button" id="btnsearch" class="btn btn-shade1 btn-sm" value="Search" /></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-content">
                        <div class="card-body">
                            <div class="form-body">
                                <div class="table-responsive">
                                    <table class="table table-sm table-bordered table-responsive-sm table-striped btn-lighten-1" id="tblDataList">
                                        <thead>
                                            <tr>
                                                <th class="text-left">Date</th>
                                                <th class="text-left">Service</th>
                                                <th class="text-left">Type</th>
                                                <th class="text-left">Mobile No.</th>
                                                <th class="text-right">Amount</th>
                                                <th class="text-center">Status</th>
                                            </tr>
                                        </thead>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
@section scripts{
    @Scripts.Render("~/bundles/datatables");
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.js"></script>
    <script>
         $(function () {
            var showMessage = '@TempData[Helper.responseStatus]'
             if (showMessage != '')
                 notifyMessage(showMessage);

             var dateFormat = "dd-mm-yy",
                from = $("#fromDate")
                    .datepicker({
                        dateFormat:"dd-mm-yy",
                        defaultDate: "+1w",
                        changeMonth: true,
                        numberOfMonths: 2
                    })
                    .on("change", function () {
                        to.datepicker("option", "minDate", getDate(this));
                    }),
                to = $("#toDate").datepicker({
                    dateFormat:"dd-mm-yy",
                    defaultDate: "+1w",
                    changeMonth: true,
                    numberOfMonths: 2
                })
                    .on("change", function () {
                        from.datepicker("option", "maxDate", getDate(this));
                    });

            function getDate(element) {
                var date;
                try {
                    date = $.datepicker.parseDate(dateFormat, element.value);
                } catch (error) {
                    date = null;
                }

                return date;
            }
         });

        $(document).ready(function () {
            if ('@Helper.doesCookieExist(Helper.userAccessToken)') {
                var fromDate = formatIndianDate(new Date(), true);
                var toDate = formatIndianDate(new Date(), false);
                $('#fromDate').val(fromDate);
                $('#toDate').val(toDate);
                bindData(fromDate, toDate);
            }
            else { window.location.href = "unauthorized";}
        });

        $('#btnsearch').click(function () {
            var fromDate = $('#fromDate').val();
            var toDate = $('#toDate').val();
            if (fromDate != '' && toDate != '') {
                bindData(fromDate, toDate);
            }else {
                notifyMessage("1|Please Select From and To Date.");
            }
        });

        function bindData(fromDate, toDate) {
            $("#tblDataList").DataTable({
                 dom: 'Blfltip',
                buttons: [
                    ['csv', 'pdf'],
                ],
                    ajax: {
                        url: '/recharge/getRechargeHistory?fromDate=' + fromDate + '&toDate=' + toDate + '',
                        type: "GET",
                        datatype: "JSON"
                    },
                    columns: [
                        {
                            data: "CreatedDateTime", "orderable": false,className:'text-left',
                            render: function (data) {
                                var dateString = data.substr(6);
                                var currentTime = new Date(parseInt(dateString));
                                var formatedDate = dateFormat(currentTime, gridDateTimeFormat);
                                var date = formatedDate;
                                return date;
                            }
                        },
                        { data: "ServiceName", name: "ServiceName",className:'text-left' },
                        { data: "ServiceType", name: "ServiceType",className:'text-left' },
                        { data: "MobileNo", name: "MobileNo",className:'text-left' },
                        { data: "Amount", name: "Amount", className: 'text-right' },
                        {
                            data: "status","orderable":false,className:'text-center',
                            render: function (data, type, objData) {
                                return (objData.status=="SUCCESS"?"<span class='badge badge-success'>Success</span>":"<span class='badge badge-danger'>"+objData.status+"</span>")
                            }
                        }
                    ],
                    processing: true,
                    destroy: true,
                    serverSide: true,
                    "order": [0, 'desc'],
                    language: {
                        processing: "<div class=\"alert alert-warning border-0 mb-2\" role=\"alert\">"+loadingDataInDataGrid+"</div>"
                    }
            });
             $("#tblDataList_length").hide();
            //$("#tblDataList_length").hide();
        }
    </script>
}